name: protoo_client
version: 0.3.3
description: Dart version of the protoo-client library.
homepage: https://github.com/cloudwebrtc/dart-protoo-client
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  events2: ^1.0.0
  retry: 3.1.1
  web_socket_channel: ^2.4.0
